// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfgNFmvCYM3nuGfM1sefgJ-FxFl9q8MPw',
    appId: '1:853567226580:web:0931ee396bf6c6bf58b141',
    messagingSenderId: '853567226580',
    projectId: 'courier-app-a8786',
    authDomain: 'courier-app-a8786.firebaseapp.com',
    storageBucket: 'courier-app-a8786.firebasestorage.app',
    measurementId: 'G-20J2YT9VJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBroao3z8390-5XdCSuxPImWM4zLvKlguY',
    appId: '1:853567226580:android:cfa88da42acfdc7158b141',
    messagingSenderId: '853567226580',
    projectId: 'courier-app-a8786',
    storageBucket: 'courier-app-a8786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB1kDirBngI4NBbtTgL0AqjOFPbEDIpQc',
    appId: '1:853567226580:ios:9295f0def9cce66058b141',
    messagingSenderId: '853567226580',
    projectId: 'courier-app-a8786',
    storageBucket: 'courier-app-a8786.firebasestorage.app',
    iosBundleId: 'com.lwm.westchester',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB1kDirBngI4NBbtTgL0AqjOFPbEDIpQc',
    appId: '1:853567226580:ios:9295f0def9cce66058b141',
    messagingSenderId: '853567226580',
    projectId: 'courier-app-a8786',
    storageBucket: 'courier-app-a8786.firebasestorage.app',
    iosBundleId: 'com.lwm.westchester',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfgNFmvCYM3nuGfM1sefgJ-FxFl9q8MPw',
    appId: '1:853567226580:web:086fc2b2ba68dfdb58b141',
    messagingSenderId: '853567226580',
    projectId: 'courier-app-a8786',
    authDomain: 'courier-app-a8786.firebaseapp.com',
    storageBucket: 'courier-app-a8786.firebasestorage.app',
    measurementId: 'G-6X06W96CS9',
  );
}
